# AgentArts Dockerfile
# Generated by AgentArts CLI

FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["python", "-c", "from app import run; run()"]
