"""
AgentArts Runtime Context

Provides runtime context management for agent execution, including
request tracking, session management, authentication, and OAuth2 flow.

The context uses Python's ``contextvars`` module to store state that is
local to the current async task or thread, making it safe for concurrent
request handling in web servers and async frameworks.

Typical usage::

    from agentarts.wrapper.runtime.context import AgentArtsRuntimeContext as ctx

    # Set values at the beginning of a request
    ctx.set_session_id("sess-abc123")
    ctx.set_request_id("req-xyz789")
    ctx.set_workload_access_token("bearer-token-...")

    # Read values anywhere in the call stack
    session_id = ctx.get_session_id()
"""

from __future__ import annotations

from contextvars import ContextVar
from typing import Any, Optional

from pydantic import BaseModel, Field




class RequestContext(BaseModel):
    """
    Immutable snapshot of the incoming request context.

    This model captures the essential fields from an HTTP request (or
    equivalent transport) so that downstream code does not need to
    depend on a specific web framework.

    Attributes:
        request_id: Unique identifier for this request, typically
            generated by the API gateway or load balancer.
        session_id: Identifier for the user session this request
            belongs to.  May be ``None`` for unauthenticated requests.
        request: The underlying framework-specific request object
            (e.g., ``fastapi.Request``), kept for advanced use-cases
            that need access to headers, query params, etc.
    """

    request_id: Optional[str] = Field(None, description="The request ID")
    session_id: Optional[str] = Field(None, description="The session ID")
    request: Optional[Any] = Field(None, description="The underlying request object")


class AgentArtsRuntimeContext:
    """
    Coroutine-safe runtime context backed by ``contextvars``.

    Every attribute is stored in its own :class:`~contextvars.ContextVar`
    so that concurrent async tasks each get their own isolated view of the
    context without any explicit locking.

    The class exposes ``get_*`` / ``set_*`` class methods for each field
    and can be used directly without instantiation::

        AgentArtsRuntimeContext.set_session_id("abc")
        AgentArtsRuntimeContext.get_session_id()  # -> "abc"

    Attributes:
        _session_id: Current session identifier.
        _request_id: Current request identifier.
        _workload_access_token: Bearer token used to call Huawei Cloud
            internal services on behalf of the workload.
        _user_id: End-user identifier (human or service account).
        _oauth2_callback_url: URL that the OAuth2 authorization server
            will redirect back to after user consent.
        _user_token: Token representing the authenticated end-user,
            distinct from the workload service token.
        _oauth2_custom_state: Opaque state string round-tripped through
            the OAuth2 authorization flow to prevent CSRF attacks.
    """

    _session_id: ContextVar[Optional[str]] = ContextVar("session_id", default=None)
    _request_id: ContextVar[Optional[str]] = ContextVar("request_id", default=None)
    _workload_access_token: ContextVar[Optional[str]] = ContextVar(
        "workload_access_token", default=None
    )

    _user_id: ContextVar[Optional[str]] = ContextVar("user_id", default=None)
    _oauth2_callback_url: ContextVar[Optional[str]] = ContextVar(
        "oauth2_callback_url", default=None
    )
    _user_token: ContextVar[Optional[str]] = ContextVar("user_token", default=None)
    _oauth2_custom_state: ContextVar[Optional[str]] = ContextVar(
        "oauth2_custom_state", default=None
    )

    # ------------------------------------------------------------------
    # session_id
    # ------------------------------------------------------------------

    @classmethod
    def get_session_id(cls) -> Optional[str]:
        """Return the current session ID, or ``None`` if not set."""
        return cls._session_id.get()

    @classmethod
    def set_session_id(cls, value: Optional[str]) -> None:
        """Set the session ID for the current context."""
        cls._session_id.set(value)

    # ------------------------------------------------------------------
    # request_id
    # ------------------------------------------------------------------

    @classmethod
    def get_request_id(cls) -> Optional[str]:
        """Return the current request ID, or ``None`` if not set."""
        return cls._request_id.get()

    @classmethod
    def set_request_id(cls, value: Optional[str]) -> None:
        """Set the request ID for the current context."""
        cls._request_id.set(value)

    # ------------------------------------------------------------------
    # workload_access_token
    # ------------------------------------------------------------------

    @classmethod
    def get_workload_access_token(cls) -> Optional[str]:
        """Return the workload access token, or ``None`` if not set."""
        return cls._workload_access_token.get()

    @classmethod
    def set_workload_access_token(cls, value: Optional[str]) -> None:
        """
        Set the workload access token.

        This token is used for authenticating calls to Huawei Cloud
        internal services (e.g., memory, MCP gateway) on behalf of
        the deployed agent workload.
        """
        cls._workload_access_token.set(value)

    # ------------------------------------------------------------------
    # user_id
    # ------------------------------------------------------------------

    @classmethod
    def get_user_id(cls) -> Optional[str]:
        """Return the current user ID, or ``None`` if not set."""
        return cls._user_id.get()

    @classmethod
    def set_user_id(cls, value: Optional[str]) -> None:
        """Set the user ID for the current context."""
        cls._user_id.set(value)

    # ------------------------------------------------------------------
    # oauth2_callback_url
    # ------------------------------------------------------------------

    @classmethod
    def get_oauth2_callback_url(cls) -> Optional[str]:
        """Return the OAuth2 callback URL, or ``None`` if not set."""
        return cls._oauth2_callback_url.get()

    @classmethod
    def set_oauth2_callback_url(cls, value: Optional[str]) -> None:
        """
        Set the OAuth2 callback URL.

        This is the URL that the OAuth2 authorization server redirects
        the user back to after the authorization flow completes.
        """
        cls._oauth2_callback_url.set(value)

    # ------------------------------------------------------------------
    # user_token
    # ------------------------------------------------------------------

    @classmethod
    def get_user_token(cls) -> Optional[str]:
        """Return the current user token, or ``None`` if not set."""
        return cls._user_token.get()

    @classmethod
    def set_user_token(cls, value: Optional[str]) -> None:
        """
        Set the user token.

        This token represents the authenticated end-user and is
        distinct from the workload service token.  It is typically
        obtained after an OAuth2 authorization code exchange.
        """
        cls._user_token.set(value)

    # ------------------------------------------------------------------
    # oauth2_custom_state
    # ------------------------------------------------------------------

    @classmethod
    def get_oauth2_custom_state(cls) -> Optional[str]:
        """Return the OAuth2 custom state, or ``None`` if not set."""
        return cls._oauth2_custom_state.get()

    @classmethod
    def set_oauth2_custom_state(cls, value: Optional[str]) -> None:
        """
        Set the OAuth2 custom state parameter.

        This opaque value is round-tripped through the OAuth2
        authorization flow to prevent cross-site request forgery (CSRF).
        """
        cls._oauth2_custom_state.set(value)

    # ------------------------------------------------------------------
    # Convenience helpers
    # ------------------------------------------------------------------

    @classmethod
    def from_request_context(cls, rc: RequestContext) -> None:
        """
        Bulk-load context fields from a :class:`RequestContext` instance.

        This is a convenience method typically called in middleware at the
        beginning of request processing.

        Args:
            rc: A :class:`RequestContext` containing the values to load.
        """
        if rc.request_id is not None:
            cls.set_request_id(rc.request_id)
        if rc.session_id is not None:
            cls.set_session_id(rc.session_id)

    @classmethod
    def to_request_context(cls) -> RequestContext:
        """
        Create a :class:`RequestContext` snapshot from the current context.

        Returns:
            A new :class:`RequestContext` populated with the current
            ``session_id`` and ``request_id`` values.
        """
        return RequestContext(
            request_id=cls.get_request_id(),
            session_id=cls.get_session_id(),
        )

    @classmethod
    def clear(cls) -> None:
        """
        Reset all context variables to ``None``.

        Call this at the end of request processing to avoid leaking
        state between requests when context vars are reused.
        """
        cls._session_id.set(None)
        cls._request_id.set(None)
        cls._workload_access_token.set(None)
        cls._user_id.set(None)
        cls._oauth2_callback_url.set(None)
        cls._user_token.set(None)
        cls._oauth2_custom_state.set(None)
